export const FETCH_FRIENDS_BEGIN = 'FETCH_FRIENDS_BEGIN';
export const FETCH_FRIENDS_SUCCESS = 'FETCH_FRIENDS_SUCCESS';
export const FETCH_FRIENDS_ERROR = 'FETCH_FRIENDS_ERROR';

export const SAVE_FRIEND_SUCCESS = 'SAVE_FRIENDS_SUCCESS';
export const SAVE_FRIEND_ERROR = 'SAVE_FRIENDS_ERROR';
export const UPDATE_FRIEND_SUCCESS = 'UPDATE_FRIENDS_SUCCESS';
export const UPDATE_FRIEND_ERROR = 'UPDATE_FRIENDS_ERROR';

export const DELETE_FRIEND_SUCCESS = 'DELETE_FRIENDS_SUCCESS';
export const DELETE_FRIEND_ERROR = 'DELETE_FRIENDS_ERROR';

export const AUTH_INIT = 'AUTH_INIT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const API_NEEDS_QUERY = 'API_NEEDS_QUERY';

