export const FETCH_FRIENDS_SUCCESS = 'FETCH_FRIENDS_SUCCESS';
export const SAVE_FRIEND_SUCCESS = 'SAVE_FRIENDS_SUCCESS';
export const SAVE_FRIEND_ERROR = 'SAVE_FRIENDS_ERROR';
export const DELETE_FRIEND_SUCCESS = 'DELETE_FRIENDS_SUCCESS';
export const DELETE_FRIEND_ERROR = 'DELETE_FRIENDS_ERROR';
