export const FRIENDS_RESET = 'FRIENDS_RESET';

export const FETCH_FRIENDS = 'FETCH_FRIENDS';
export const FETCH_FRIENDS_SUCCESS = 'FETCH_FRIENDS_SUCCESS';
export const FETCH_FRIENDS_ERROR = 'FETCH_FRIENDS_ERROR';

export const CREATE_FRIEND = 'CREATE_FRIENDS';
export const CREATE_FRIEND_SUCCESS = 'CREATE_FRIENDS_SUCCESS';
export const CREATE_FRIEND_ERROR = 'CREATE_FRIENDS_ERROR';
